# Generated by Django 3.2 on 2021-04-24 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='holiday name')),
                ('name_local', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description about holiday')),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('date_year', models.CharField(blank=True, max_length=10, null=True)),
                ('date_month', models.CharField(blank=True, max_length=5, null=True)),
                ('date_day', models.CharField(blank=True, max_length=5, null=True)),
                ('week_day', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
